# Application name
spring.application.name=FirstHtmlPage

# Database connection (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/Todo
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true   
spring.sql.init.mode=always

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JSP view resolver
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# Logging levels
logging.level.org.springframework=INFO
logging.level.com.springboot.todo=INFO   
# Date format for MVC binding
spring.mvc.format.date=yyyy-MM-dd


